POST http://localhost:3000/register
content-type: application/json

{
    "username": "hugh",
    "password": "pass"
}

###

POST http://localhost:3000/login
content-type: application/json

{
    "username": "hugh",
    "password": "pass2"
}

###

POST http://localhost:3000/passChange
content-type: application/json

{
    "username": "hugh",
    "password": "pass",
    "newPassword": "pass2"
}

###

POST http://localhost:3000/addLocation
content-type: application/json

{
    "username": "hugh",
    "password": "pass2",
    "location": "France"
}

###

POST http://localhost:3000/getLocations
content-type: application/json

{
    "username": "hugh",
    "password": "pass2"
}

###

POST http://localhost:3000/deleteLocation
content-type: application/json

{
    "username": "hugh",
    "password": "pass2",
    "location": "France"
}

